---
apiVersion: v1
kind: Service
metadata:
  name: imgtxt-service
spec:
  ports:
  - port: 8000
    nodePort: 30001
    targetPort: imgtxt-port
    protocol: TCP
  selector: 
       app: imgtxt
  type: NodePort
